### ISSUE TITLE
Javamelody swallows response if Spring WebAsyncTask/Callable is used

### ISSUE THREAD

**Issue by GoogleCodeExporter** [evernat/javamelody#338]
```
What steps will reproduce the problem?
1. unzip test.zip
2. build maven test project
3. run without javamelody, http://localhost:8080/test/test -> all working
4. uncomment javamelody in pom.xml and rebuild
5. run with javamelody, http://localhost:8080/test/test -> async tests failing 
with empty response except @ResponseBody or redirect:/ is used

What is the expected output? What do you see instead?
All should work

What version of the product are you using? On what application server, JDK,
operating system?
   Java 6 or 7
   Tomcat 7.0.42


Please provide any additional information below.


```

Original issue reported on code.google.com by `mfrey0@gmail.com` on 10 Sep 2013 at 1:24

Attachments:
* [test.zip](https://storage.googleapis.com/google-code-attachments/javamelody/issue-338/comment-0/test.zip)

**Comment by evernat** [comment]
After a discussion with Mark from Tomcat an issue was created there:
https://bz.apache.org/bugzilla/show_bug.cgi?id=58063

And Violeta has written an answer:
In Javamelody web fragment, the filter MonitoringFilter must specify dispatcher type ASYNC.

Regards,
Violeta

E.g.
	<filter-mapping>
		<filter-name>javamelody</filter-name>
		<url-pattern>/*</url-pattern>
                <dispatcher>REQUEST</dispatcher>
                <dispatcher>ASYNC</dispatcher>
	</filter-mapping>

This answer closes this quite old defect and Violeta Georgieva can be thanked for that.

This is merged in master (2bb18a6f2d7aefdbf8eda489fd68f57487e67570) and ready for the next release (1.57).
The [web.xml example](../../blob/wiki/UserGuide.md#2-webxml-file) in UserGuide is also fixed.
